### ISSUE TITLE
Launch?

### ISSUE THREAD

**Issue by awfrancisco** [18F/design-principles-guide#6]
Has this guide been officially launched? Is it ready to be added to the Guides homepage and get it's own blog post?

**Comment by esgoodman** [comment]
What does "launch" mean in this context?

**Comment by awfrancisco** [comment]
Tell the public about it through a blog post and then add it to the Guides homepage. I'm mostly asking if there's continuing work that is being done before this reaches MVP status. If not, I'd love to facilitate getting this out in front of the public.

**Comment by esgoodman** [comment]
Nope, we are ready for MVP. ccing @bradnunnally, but I know he's busy right now.

**Comment by bradnunnally** [comment]
It's good to go from my point of view.

**Comment by bradnunnally** [comment]
Let me know if you need any help with anything getting this out.

**Comment by awfrancisco** [comment]
Great. I think we can put it up on the [Guides homepage](https://pages.18f.gov/guides/), and then we can work on the blog post. I've created an [issue here](https://github.com/18F/blog-drafts/issues/280). Can your team go into the original comment on the issue and edit the audience/goal/description for what you'd like in this post? And then someone from the team can start a draft, or we can have someone from the comms team interview one of you and then write up the launch post.
